import type { Metadata } from "next";
import Link from "next/link";
import { Sparkles } from "lucide-react";
import { ThemeToggle } from "@/components/shared/theme-toggle";

export const metadata: Metadata = {
  title: "Terms of Service",
  description:
    "Terms of Service for Flashtar — AI-powered flashcard generation platform. Read our terms before using the service.",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen flex flex-col">
      <header className="sticky top-0 z-50 border-b bg-background/80 backdrop-blur-sm">
        <div className="container mx-auto flex h-16 items-center justify-between px-4">
          <Link href="/" className="flex items-center gap-2 font-bold text-xl">
            <Sparkles className="h-6 w-6 text-primary" />
            Flashtar
          </Link>
          <ThemeToggle />
        </div>
      </header>

      <main className="flex-1 container mx-auto px-4 py-16 max-w-3xl">
        <h1 className="text-3xl md:text-4xl font-bold mb-2">
          Terms of Service
        </h1>
        <p className="text-muted-foreground mb-10">
          Last updated: June 15, 2026
        </p>

        <div className="prose prose-neutral dark:prose-invert max-w-none space-y-8">
          <p>
            By accessing or using Flashtar (&quot;the Service&quot;), you agree
            to be bound by these Terms of Service. If you do not agree, please
            do not use the Service.
          </p>

          <section>
            <h2 className="text-xl font-semibold mb-3">Service Operator</h2>
            <p className="text-muted-foreground leading-relaxed">
              Flashtar is operated by Promptback (&quot;Promptback&quot;,
              &quot;we&quot;, &quot;us&quot;, or &quot;our&quot;). Promptback is
              the legal entity responsible for operating the Flashtar service
              available at{" "}
              <a
                href="https://flashtar.app"
                className="text-primary hover:underline"
              >
                https://flashtar.app
              </a>
              . All references to &quot;Flashtar&quot; within these Terms refer
              to the products and services provided by Promptback.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">1. Service</h2>
            <p className="text-muted-foreground leading-relaxed">
              Flashtar is a platform that allows users to generate, edit,
              manage, and export AI-powered flashcard decks for personal and
              educational use. The Service leverages artificial intelligence to
              create flashcard content based on user-provided prompts.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">2. User Accounts</h2>
            <p className="text-muted-foreground leading-relaxed">
              You must create an account to use the Service. You are responsible
              for maintaining the security of your account credentials and for
              all activity that occurs under your account. You must provide
              accurate and complete information when creating your account.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">3. Acceptable Use</h2>
            <p className="text-muted-foreground leading-relaxed">
              You agree not to use the Service to generate, store, or distribute
              content that is illegal, harmful, abusive, defamatory, or
              otherwise objectionable. You may not attempt to reverse engineer,
              exploit, or abuse the Service or its AI generation capabilities.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">
              4. AI-Generated Content
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              Content generated by the AI may contain inaccuracies, errors, or
              outdated information. Promptback does not guarantee the accuracy,
              completeness, or reliability of any AI-generated content. Users
              are solely responsible for reviewing and verifying all generated
              flashcards before use. AI-generated content should not be used as
              a substitute for professional advice.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">
              5. Subscriptions &amp; Payments
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              Certain features of the Service require a paid subscription.
              Payments are processed through third-party payment providers,
              specifically Paddle as Merchant of Record. By subscribing, you
              authorize recurring charges at the applicable rate. You may cancel
              your subscription at any time through your account settings, and
              access to paid features will continue until the end of your
              current billing period.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">
              6. Intellectual Property
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              You retain ownership of the content you create, including
              flashcards and decks. By using the Service, you grant Promptback a
              limited license to process your content for the purpose of
              providing the Service. The Flashtar platform, branding, and
              underlying technology remain the property of Promptback.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">7. Termination</h2>
            <p className="text-muted-foreground leading-relaxed">
              We reserve the right to suspend or terminate accounts that violate
              these Terms, engage in abusive behavior, or use the Service in a
              manner that negatively impacts other users or the platform. You
              may delete your account at any time by contacting us.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">
              8. Limitation of Liability
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              To the maximum extent permitted by law, Promptback (operating
              Flashtar) shall not be liable for any indirect, incidental,
              special, consequential, or punitive damages arising from your use
              of the Service. This includes, but is not limited to, damages
              resulting from reliance on AI-generated content, loss of data, or
              service interruptions.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">
              9. Changes to These Terms
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              We may update these Terms from time to time. We will notify users
              of material changes via email or through the Service. Continued
              use of the Service after changes take effect constitutes
              acceptance of the updated Terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">10. Contact</h2>
            <p className="text-muted-foreground leading-relaxed">
              If you have questions about these Terms, please contact us at{" "}
              <a
                href="mailto:support@flashtar.app"
                className="text-primary hover:underline"
              >
                support@flashtar.app
              </a>
              .
            </p>
          </section>
        </div>
      </main>

      <footer className="border-t py-8">
        <div className="container mx-auto px-4">
          <div className="flex flex-col sm:flex-row justify-between items-center gap-4 text-sm text-muted-foreground">
            <Link
              href="/"
              className="flex items-center gap-2 font-bold text-foreground"
            >
              <Sparkles className="h-4 w-4 text-primary" />
              Flashtar
            </Link>
            <div className="flex gap-4">
              <Link href="/terms" className="hover:text-foreground">
                Terms
              </Link>
              <Link href="/privacy" className="hover:text-foreground">
                Privacy
              </Link>
              <Link href="/refund" className="hover:text-foreground">
                Refunds
              </Link>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
}
